### PR TITLE
fix(v2): add USDT_MATIC swap support

### LINKED ISSUE #7: 2.0.0-beta.1 is missing USDT_MATIC / Ticker.USDT support
## Summary

In practice, downstream consumers need to patch the package to add:

- `Ticker.USDT`
- `AssetId.USDT_MATIC`
- `Precision.USDT = 6`
- the `AssetId.USDT_MATIC -> Ticker.USDT` mapping in `dist/helpers.js`

Without that patch, the USDT -> BTC Lightning swap flow breaks.

## Affected version

- `@nimiq/fastspot-api@2.0.0-beta.1`

## Actual behavior

Two concrete failures show up downstream:

1. `createSwap({ asset: AssetId.USDT_MATIC }, ...)` fails validation because `AssetId.USDT_MATIC` is missing from the published enum surface, which leads to runtime errors like:
   - `Unknown SELL asset`

2. Quote/swap fee conversion for USDT-backed swaps is incomplete because the published package is missing `Ticker.USDT` and `Precision.USDT`, so USDT fee amounts cannot be converted correctly.

## Expected behavior

The published beta should expose the same USDT Polygon asset/ticker surface needed to:

- request `USDT_MATIC` swaps
- convert USDT fees
- treat USDT with 6 decimals

## Downstream patch currently required

We currently have to patch the installed package like this:

```diff
--- a/dist/helpers.js
+++ b/dist/helpers.js
@@
         case AssetId.USDC_MATIC: return Ticker.USDC;
+        case AssetId.USDT_MATIC: return Ticker.USDT;
         case AssetId.EUR: return Ticker.EUR;
```

```diff
--- a/dist/types.d.ts
+++ b/dist/types.d.ts
@@
 export declare enum Ticker {
     NIM = "NIM",
     BTC = "BTC",
     USDC = "USDC",
+    USDT = "USDT",
     EUR = "EUR"
 }
@@
 export declare enum AssetId {
     NIM = "NIM",
     BTC = "BTC",
     BTC_LN = "BTC_LN",
     USDC_MATIC = "USDC_MATIC",
+    USDT_MATIC = "USDT_MATIC",
     EUR = "EUR"
 }
@@
 export declare const Precision: {
     readonly NIM: 5;
     readonly BTC: 8;
     readonly USDC: 6;
+    readonly USDT: 6;
     readonly EUR: 2;
     readonly USD: 2;
 };
```

### PR DESCRIPTION
**Pull request by Albermonte**
## Summary
- add `Ticker.USDT` to the v2 API surface
- add `AssetId.USDT_MATIC` and `Precision.USDT = 6`
- map `AssetId.USDT_MATIC` to `Ticker.USDT` during quote conversion

## Verification
- `npm run prepare`
- verified the generated `dist` output contains the missing USDT symbols from #7

Closes #7

### CODE REVIEW

File: src/helpers.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ function assetToTicker(asset: AssetId): Ticker {
         case AssetId.NIM: return Ticker.NIM;
         case AssetId.BTC: return Ticker.BTC;
         case AssetId.BTC_LN: return Ticker.BTC;
+        case AssetId.USDT_MATIC: return Ticker.USDT;
         case AssetId.USDC_MATIC: return Ticker.USDC;
```
Comment (sisou) [inline src/helpers.ts:42]: Since T comes after C, I would like all USDT mentions to be after USDC.

**Review by sisou — APPROVED** [review]
